# Generated by Django 4.2.5 on 2023-09-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
