# Generated by Django 4.2.5 on 2023-09-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_profileimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='profileImage',
            new_name='profileIm',
        ),
    ]
